### ISSUE TITLE
Add non-cdisc examples to the modules

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.modules.general#29]
Modules without a non-cdisc example:
* [x] tm_a_pca
* [x] tm_a_regression _bug detected (BLOCKER!)_ https://github.com/insightsengineering/teal.slice/issues/560
* [x] tm_data_table
* [x] tm_g_association _bug detected_ https://github.com/insightsengineering/teal.modules.general/issues/645
* [x] tm_g_bivariate
* [x] tm_g_response
* [x] tm_g_scatterplot
* [x] tm_g_scatterplotmatrix
* [x] tm_missing_data
* [x] tm_outliers _bugs detected_ https://github.com/insightsengineering/teal.modules.general/issues/648, https://github.com/insightsengineering/teal.modules.general/issues/650
* [x] tm_t_crosstable _bug detected_ https://github.com/insightsengineering/teal.modules.general/issues/649
* [x] tm_variable_browser

Provenance: 
```
Creator: kpagacz
```

**Comment by chlebowa** [comment]
Do we want to add non-CDISC examples or replace CDISC examples with ones with normal data?

**Comment by m7pr** [comment]
Maybe we can replace all examples with normal data and remove evertyhing we have under `data/` folder https://github.com/insightsengineering/teal.modules.general/tree/main/data is they are not included in the vignettes?

**Comment by donyunardi** [comment]
> Do we want to add non-CDISC examples or replace CDISC examples with ones with normal data?

We want to add non-cdisc examples, in addition of the cdisc example one.

**Comment by chlebowa** [comment]
> > Do we want to add non-CDISC examples or replace CDISC examples with ones with normal data?
> 
> We want to add non-cdisc examples, in addition of the cdisc example one.

Very well, the PR is ready for review. The bugs mentioned above remain to be fixed and it would be good to solve them before release but are not hard blockers.
