### ISSUE TITLE
Pre-release activities

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.modules.general#624]
## Package level checks
* https://github.com/insightsengineering/teal.modules.general/pull/639
* Review and update:
    * README.md (check example code)
    * NEWS.md
* Run urlchecker::url_check() to identify broken links and fix
* Run R CMD check --as-cran make sure everything pass
* Package `Title` is not duplicated in Package `Description` in DESCRIPTION file (e.g. this happens in teal.slice currently)
* All package names in `Title` and `Description` fields of DESCRIPTION file are quoted with `'`
* You have checked the Package Release Template https://github.com/insightsengineering/teal.reporter/pull/205/files
* Make sure all `teal.*` mentions are lower-cased and quoted
* Make Sure inst/WORDLIST is minimalized
* Make sure each link to our documentation hosted with pkgdown on github pages do not have `/main/` in the address but it has `/latest/` instead, so we always expose the documentation of the latest release and not what's currently on main branch but not yet released,
* Remove exception in .lintr: indentation_linter = NULL
* Remove @noMd (in favor of Roxygen: list(markdown = TRUE) in DESCRIPTION)

## Vignettes level checks
* https://github.com/insightsengineering/teal.modules.general/issues/640
* Sanity check of all vignettes, make sure there is no typo, no wrong format, etc.

## Non-exported functions level checks
* https://github.com/insightsengineering/teal.modules.general/issues/641
* Make sure non-exported functions do not have examples

## Exported functions level checks
* Review functions:
    * @example tag, make sure it runs, fix if otherwise
    * Make sure functions has @return tag to document the return value
    * no \dontrun tag, replace with if(interactive()) if needed
    *  Standard order of roxygen2 tags
    * `@title ➡️ @doctype ➡️ @description ➡️ @details ➡️ @rdname ➡️` 
    * `➡️ @inheritParams ➡️ @params ➡️ @return ➡️ @seealso ➡️ @references ➡️`
    * `➡️ @examples ➡️ @export ➡️ @keywords  ➡️  @noRd`
* Make sure there are no `:::` in examples
    * if you need to retain the example that uses `:::`, use `getFromNamespace()` function.
* Remove return wrapper if it is the last expression (per NEST guidelines)

Please self-assign by your name next to the module and link to the PR:
- [x] tm_g_response.R @averissimo #666
- [x] tm_file_viewer.R @averissimo #665
- [x] tm_t_crosstable.R @averissimo #664
- [x] tm_g_distribution.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/669
- [x] tm_data_table.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/667
- [x] tm_missing_data.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/668
- [x] tm_g_bivariate.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/660
- [x] tm_g_scatterplotmatrix.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/661
- [x] tm_outliers.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/653
- [x] tm_g_scatterplot.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/657
- [x] tm_front_page.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/654
- [x] tm_a_pca.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/646
- [x] tm_variable_browser.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/652
- [x] tm_a_regression.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/655
- [x] tm_g_association.R @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/656
- [x] Rest of R files @kartikeyakirar https://github.com/insightsengineering/teal.modules.general/pull/676

extra:

- Add common `@return` tag #670
- Standard function title format in docs https://github.com/insightsengineering/teal.modules.general/pull/691

## Potential removal of dependencies

Consider:

- #643
- [x] Removal of `{magrittr}` by importing pipe operator from `{dplyr}`   :heavy_check_mark: _done_
- [x] Other packages that can be easily removed   :heavy_check_mark: removed `tidyselect` as its functions are reexported from `dplyr`
- Move any of the packages from `Depends` -> `Imports`
  - [x] `{ggmosaic}`   :x: _impossible_ (see on issue)
  - [x] `{ggplot2}`   :x: _impossible_ (see on issue)
  - [x] `{shinyTree}`   :heavy_check_mark: _done_
  - [x] `{teal.transform}`   :x: _valid_: `teal.transform` functions should be available to `tmg` users
  - [x] `{teal}`   :x: _valid_: `teal` dependency is standard in all module packages
  - [x] `{shiny}`   :x: _valid_: like `teal`, module packages use `shiny` extensively
- [x] Make sure `Config/Needs/verdepcheck` and `pre-commit` config are updated
  - https://github.com/insightsengineering/teal.modules.general/pull/683
 
## Update and Apply the Latest Roxygen Documentation Tags

1. https://github.com/insightsengineering/teal.modules.general/issues/647

## Unused functions

- #642
- [x] Identify internal functions that are not used (if they exist)
- Discuss case by case if they should be removed

## Replace `val_labels` with `col_labels`
- https://github.com/insightsengineering/teal.modules.general/issues/658

## Correct linting
- #670

## Standardize `option` Notation
- https://github.com/insightsengineering/teal.modules.general/issues/674

**Comment by m7pr** [comment]
Hey @insightsengineering/nest-core-dev based on the flow I've observed during other pre-release activities in our package I allowed myself to divide this card into smaller activities

- Package level checks
- Vignettes level checks
- Exported functions level checks
- Non-exported functions level checks

I hope this will allow more people to be included in the collaboration in this process and will make the review process easier. Please make all PRs to pre-release branch, but please do not merge, even when a PR is reviewed and approved. We will merge everything, the moment all PRs to pre-release branch are approved and pre-release is also approved. My proposition is to have a pre-release branch be a branch where we review Package-level checks and then merge all other activities in there, before merging to main.

**Comment by averissimo** [comment]
Agree!

**Comment by chlebowa** [comment]
While looking around for unused functions, I came upon `add_facet_labels` which is exported but not necessarily should be. Should we look for cases like that as well? Do we have time for such an assessment?

**Comment by m7pr** [comment]
@chlebowa maybe it's a good comment for https://github.com/insightsengineering/teal.modules.general/pull/659 ?
If function is not used in any teal package nor in teal gallery it does not need to be exported.

It is used only in `teal.modules.general` in `tm_g_bivariate` so prefixing should be enough and no need for exporting. Examples can be extended for this function with `getFromNamespace()` (and potentially be removed for CRAN release)

<img width="866" alt="image" src="https://github.com/insightsengineering/teal.modules.general/assets/133694481/50e31053-8a33-4cc1-a233-8043e9629bd9">

**Comment by chlebowa** [comment]
Prefixing is only for foreign functions. This function (looks to me) is defined in `tmg` and only used in `tmg` functions with no apparent exposure to a `teal` app developer. A function like that should not be exported.

But perhaps there is another reason for this particular function to be exported?

**Comment by averissimo** [comment]
Agree! How did you find this function? Is it an easy process or heavily manual?

**Comment by m7pr** [comment]
For the automation, maybe there is a way you can list of functions and then grep it's appearance in a directory that contains all teal packages and teal,gallery. And sort functions by the number of apperances, so that the least frequent one can be examined manually?

**Comment by kartikeyakirar** [comment]
From the namespace file, we can directly check all the exported functions such as `add_facet_labels` and `get_scatterplotmatrix_stats`. However, both of these functions are exported and should be internal. I checked this by searching for these functions on the Github organization page.

**Comment by chlebowa** [comment]
I did use the GH search bar to see if it's used in different packages but that is never the first place that I go. It ignores special characters and chops up queries on white space.

**Comment by averissimo** [comment]
For documentation simplicity and removal of repetitive `@return` tags I suggest to:

1. Add to `#' @return Object of class `teal_module` to be used in `teal` applications` to `shared_params`
    - `R/utils.R`
2. Use `#' @inherit shared_params return` on all the modules

----

We should also add a task to this issueto remove all linter errors.

![image](https://github.com/insightsengineering/teal.modules.general/assets/211358/403c2100-8b08-411b-b942-ce6cb36e4fc2)

**Comment by kartikeyakirar** [comment]
> For documentation simplicity and removal of repetitive @return tags I suggest to:

I agree,

**Comment by m7pr** [comment]
@averissimo would you like to take the lead on your propositions, or do you need our help?

**Comment by averissimo** [comment]
I'll do it :+1:

**Comment by m7pr** [comment]
I think we can merge #670 into here, and then pull changes to all other PRs that we have for functions

**Comment by averissimo** [comment]
@kartikeyakirar found an interesting thing on the documentation about the `@template` tag

Q: Should we keep using the `@template` tag?  _(it has been superseded)_
_take a look at `man-roxygen/ggplot2_args_multi.R` and search for `ggplot_2_args_multi`_

If we stop using it, we can add this parameter to the `shared_params` definition and add the custom information to `@details`

#### Context

`{tmg}` is using the `@template` roxygen tag to add a "customizable" parameter `ggplot2_args`. 

This template allows a special `<%=ggnames%>` string that defines a placeholder for a `ggnames` variable and, thus, has a custom documentation for each time it's used. _(to supply different allowable values)_

This tag has been [superseded](https://roxygen2.r-lib.org/articles/reuse.html?q=template#superseded) by `{roxygen2}` in favour of inline code.

----

I don't see an immediate need to remove this tag as long as it's not deprecated. It seems useful and removes duplicated code.

If we keep it, I think we should move the file `man-roxygen/ggplot2_args_multi.R` to `man/roxygen/template/ggplot2_args_multi.R` (and make the corresponding change to `.Rbuildignore`)

**Comment by donyunardi** [comment]
All works are completed.
Closing,
