### ISSUE TITLE
[Bug]: modules crash if package not attached

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.modules.general#786]
### What happened?

Unless the package is attached, at least some modules fail.
THIS IS A TWO-PART ISSUE

### PART 1

`teal.modules.general` seems to rely on the `magrittr` pipe but does not re-export it.
```
teal_app <- teal::init(
  data = teal.data::teal_data(ADSL = teal.modules.general::rADSL),
  modules = teal::modules(teal.modules.general::tm_missing_data())
)
shiny::runApp(teal_app)
```
![image](https://github.com/user-attachments/assets/52fe839c-ff94-45b1-981d-6b48758b27f0)

I suggest re-exporting the pipe operator OR replacing it with the native pipe.
_Be careful with native pipe, it changes how the call looks like:_

```r
quote(a |> foo() |> foo2())
# foo2(foo(a))
```

### PART 2

`tm_missing_data` (and possibly other modules) requires `ggplot2` to be attached (`ggplot` function used without prefix) but does not enforce attaching, unless it is itself attached.

```
library(magrittr)
teal_app <- teal::init(
  data = teal.data::teal_data(ADSL = teal.modules.general::rADSL),
  modules = teal::modules(teal.modules.general::tm_missing_data())
)
shiny::runApp(teal_app)
```

![image](https://github.com/user-attachments/assets/3a7f9ce5-03d4-44ab-ad7d-a673c30b1193)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
Makes sense. We removed re-export of the `magrittr`recently so we should fix the modules now. @donyunardi

**Comment by chlebowa** [comment]
I think the native pipe is safe to use now 👍

**Comment by gogonzo** [comment]
> I think the native pipe is safe to use now 👍

I think it is, R 4.1 released in May 2021 (pipe where introduced then), it has been more than 3 years. Most of the systems have updated already (I hope so)

**Comment by chlebowa** [comment]
After the `.rds` debacle many systems may be using R 4.4 already 😉
